#!/usr/bin/env bash
# Regenerates ../setup.sh, embedding the current repo files so setup.sh can
# bootstrap webterm on a machine without cloning the repo.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$REPO_DIR/setup.sh"
MARK=__WEBTERM_EOF__

FILES=(
  package.json
  package-lock.json
  .gitignore
  server.js
  public/index.html
  public/app.js
  systemd/webterm.socket
  systemd/webterm.service.template
  scripts/install-systemd.sh
  scripts/uninstall-systemd.sh
  test/smoke.js
)

{
  cat <<'HEAD'
#!/usr/bin/env bash
# webterm bootstrap: writes the project files, installs dependencies and
# enables the systemd user socket so http://localhost:3000 starts on demand.
#
# GENERATED by scripts/gen-setup.sh - edit the source files, then regenerate.
#
# Usage: ./setup.sh [--dir DIR] [--tmux] [--no-service]
#   --dir DIR      install location (default: $HOME/webterm)
#   --tmux         run the shell inside tmux (sessions survive tab closes)
#   --no-service   only write files and npm install; don't touch systemd
set -euo pipefail

TARGET="$HOME/webterm"
TMUX_MODE=0
SERVICE=1
while [ $# -gt 0 ]; do
  case "$1" in
    --dir) TARGET="${2:?--dir needs a value}"; shift 2 ;;
    --tmux) TMUX_MODE=1; shift ;;
    --no-service) SERVICE=0; shift ;;
    -h|--help) sed -n '2,10p' "$0"; exit 0 ;;
    *) echo "Unknown option: $1" >&2; exit 2 ;;
  esac
done

die() { echo "error: $*" >&2; exit 1; }

# --- prerequisites -----------------------------------------------------------
missing=()
command -v node >/dev/null || missing+=(nodejs)
command -v npm >/dev/null || missing+=(npm)
command -v make >/dev/null || missing+=(make)
command -v g++ >/dev/null || command -v c++ >/dev/null || missing+=(g++)
command -v python3 >/dev/null || missing+=(python)
if [ "$TMUX_MODE" = 1 ]; then command -v tmux >/dev/null || missing+=(tmux); fi
if [ ${#missing[@]} -gt 0 ]; then
  echo "Missing: ${missing[*]}" >&2
  echo "node-pty compiles a native module, so build tools are required." >&2
  echo "  Arch:    sudo pacman -S --needed base-devel python nodejs npm tmux" >&2
  echo "  SteamOS: see 'SteamOS notes' in the README (rootfs is read-only)." >&2
  exit 1
fi
node_major="$(node -p 'process.versions.node.split(".")[0]')"
[ "$node_major" -ge 18 ] || die "Node >= 18 required (found $(node -v))"

# --- write files -------------------------------------------------------------
echo "Writing files to $TARGET"
mkdir -p "$TARGET"
cd "$TARGET"
mkdir -p public systemd scripts test
HEAD

  for f in "${FILES[@]}"; do
    grep -q "$MARK" "$REPO_DIR/$f" && { echo "$f contains $MARK" >&2; exit 1; }
    printf "\ncat > '%s' <<'%s'\n" "$f" "$MARK"
    cat "$REPO_DIR/$f"
    printf '%s\n' "$MARK"
  done

  cat <<'TAIL'

chmod +x scripts/*.sh

# --- install dependencies ----------------------------------------------------
echo "Installing npm dependencies (builds node-pty)..."
npm ci --no-audit --no-fund

if [ "$SERVICE" = 0 ]; then
  echo "Done. Start it manually with: cd '$TARGET' && npm start"
  exit 0
fi

# --- systemd user socket -----------------------------------------------------
command -v systemctl >/dev/null || die "systemctl not found; rerun with --no-service"
systemctl --user show-environment >/dev/null 2>&1 \
  || die "no systemd user session (log in graphically or via ssh, not su/sudo)"

bash scripts/install-systemd.sh

DROPIN="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user/webterm.service.d"
if [ "$TMUX_MODE" = 1 ]; then
  mkdir -p "$DROPIN"
  printf '[Service]\nEnvironment=WEBTERM_TMUX=1\n' > "$DROPIN/tmux.conf"
else
  rm -f "$DROPIN/tmux.conf"
fi
systemctl --user daemon-reload

# Poke the socket once to prove activation works (server exits again when idle)
if command -v curl >/dev/null; then
  if curl -fsS --noproxy '*' -o /dev/null --max-time 10 http://127.0.0.1:3000/; then
    echo "Check: http://localhost:3000 answered, socket activation works."
  else
    echo "warning: http://localhost:3000 did not answer; see: journalctl --user -u webterm.service" >&2
  fi
fi
systemctl --user --no-pager status webterm.socket | head -n 3 || true
TAIL
} > "$OUT"
chmod +x "$OUT"
echo "Wrote $OUT"
